### ISSUE TITLE
500 error creating case

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#8]
I upgraded python to 3.5 (doesn't work on 2.7 because of `super()`) but I'm still getting a 500 error.

**Request**

``` bash
curl 'http://localhost:8000/api/travel-request/' -H 'Pragma: no-cache' -H 'Origin: http://localhost:9966' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2853.0 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:9966/travel-request' -H 'Connection: keep-alive' --data-binary '{"name":"Tim Wisniewski","destination":"Morocco","cost":"3500","supervisor_email":"secret.squirrel@mailinator.com"}' --compressed
```

**Response**

```
HTTP/1.0 500 Internal Server Error
Date: Wed, 28 Sep 2016 12:06:40 GMT
Server: WSGIServer/0.2 CPython/3.5.2
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
Content-Type: text/html
```

'NoneType' object has no attribute 'actions'
`/Users/tim/Sites/stately/server/src/stately/views.py in serialize_case, line 30`
[Full response](http://codepen.io/timwis/full/dpRJpZ/)

**Comment by mjumbewu** [comment]
I think this should be fixed as of commit 57abf38. If not, lemme know.

**Comment by timwis** [comment]
Fixed, thanks!
